#!/bin/bash

javac AddPuzzleSpreadsheet.java -sourcepath .:/canadia/google/gdata/java/src/:/canadia/google/gdata/java/ -cp .:/canadia/google/gdata/java/classes/:/canadia/google/gdata/java/sample/appsforyourdomain/classes/:/canadia/google/commons-cli-1.2/commons-cli-1.2.jar:/usr/share/tomcat6/lib/servlet-api.jar:/usr/share/java/gnumail.jar:/usr/share/java/activation.jar:/canadia/google/gdata/java/deps/google-collect-1.0-rc1.jar:/canadia/google/gdata/java/deps/jsr305.jar -Xlint:unchecked  -Xlint:deprecation 

javac AddRound.java -sourcepath .:/canadia/google/gdata/java/src/:/canadia/google/gdata/java/ -cp .:/canadia/google/gdata/java/classes/:/canadia/google/gdata/java/sample/appsforyourdomain/classes/:/canadia/google/commons-cli-1.2/commons-cli-1.2.jar:/usr/share/tomcat6/lib/servlet-api.jar:/usr/share/java/gnumail.jar:/usr/share/java/activation.jar:/canadia/google/gdata/java/deps/google-collect-1.0-rc1.jar:/canadia/google/gdata/java/deps/jsr305.jar -Xlint:unchecked  -Xlint:deprecation 

javac AddHunt.java -sourcepath .:/canadia/google/gdata/java/src/:/canadia/google/gdata/java/ -cp .:/canadia/google/gdata/java/classes/:/canadia/google/gdata/java/sample/appsforyourdomain/classes/:/canadia/google/commons-cli-1.2/commons-cli-1.2.jar:/usr/share/tomcat6/lib/servlet-api.jar:/usr/share/java/gnumail.jar:/usr/share/java/activation.jar:/canadia/google/gdata/java/deps/google-collect-1.0-rc1.jar:/canadia/google/gdata/java/deps/jsr305.jar -Xlint:unchecked  -Xlint:deprecation 

javac DeleteEntries.java -sourcepath .:/canadia/google/gdata/java/src/:/canadia/google/gdata/java/ -cp .:/canadia/google/gdata/java/classes/:/canadia/google/gdata/java/sample/appsforyourdomain/classes/:/canadia/google/commons-cli-1.2/commons-cli-1.2.jar:/usr/share/tomcat6/lib/servlet-api.jar:/usr/share/java/gnumail.jar:/usr/share/java/activation.jar:/canadia/google/gdata/java/deps/google-collect-1.0-rc1.jar:/canadia/google/gdata/java/deps/jsr305.jar -Xlint:unchecked  -Xlint:deprecation 

javac AddDomainUser.java -sourcepath .:/canadia/google/gdata/java/src/:/canadia/google/gdata/java/ -cp .:/canadia/google/gdata/java/classes/:/canadia/google/gdata/java/sample/appsforyourdomain/classes/:/canadia/google/commons-cli-1.2/commons-cli-1.2.jar:/usr/share/tomcat6/lib/servlet-api.jar:/usr/share/java/gnumail.jar:/usr/share/java/activation.jar:/canadia/google/gdata/java/deps/google-collect-1.0-rc1.jar:/canadia/google/gdata/java/deps/jsr305.jar -Xlint:unchecked  -Xlint:deprecation 

javac DeleteDomainUser.java -sourcepath .:/canadia/google/gdata/java/src/:/canadia/google/gdata/java/ -cp .:/canadia/google/gdata/java/classes/:/canadia/google/gdata/java/sample/appsforyourdomain/classes/:/canadia/google/commons-cli-1.2/commons-cli-1.2.jar:/usr/share/tomcat6/lib/servlet-api.jar:/usr/share/java/gnumail.jar:/usr/share/java/activation.jar:/canadia/google/gdata/java/deps/google-collect-1.0-rc1.jar:/canadia/google/gdata/java/deps/jsr305.jar -Xlint:unchecked  -Xlint:deprecation 
